"""Prometheus metrics for the VirusScanner Producer."""

from prometheus_client import Counter, Gauge, Histogram

# --- Request-level metrics ---

REQUESTS_TOTAL = Counter(
    "producer_requests_total",
    "Total ext_proc requests processed",
    ["method", "result"],
)

REQUEST_DURATION = Histogram(
    "producer_request_duration_seconds",
    "End-to-end ext_proc request duration (header-in to body-out)",
    ["method"],
    buckets=[0.1, 0.5, 1, 2, 5, 10, 30, 60, 120, 300],
)

# --- Scan session metrics ---

SCAN_SESSIONS = Counter(
    "producer_scan_sessions_total",
    "Scan sessions by outcome",
    ["result"],
    # result: accepted, bypassed_congestion, bypassed_handshake, cache_hit, infected, clean, error
)

ACTIVE_SESSIONS = Gauge(
    "producer_active_sessions",
    "Number of currently in-flight scan sessions",
)

# --- Size metrics ---

BODY_SIZE_BYTES = Histogram(
    "producer_body_size_bytes",
    "Total body size per scan request in bytes",
    ["method"],
    buckets=[
        1024,                   # 1 KB
        10 * 1024,              # 10 KB
        100 * 1024,             # 100 KB
        1024 * 1024,            # 1 MB
        10 * 1024 * 1024,       # 10 MB
        100 * 1024 * 1024,      # 100 MB
        1024 * 1024 * 1024,     # 1 GB
        10 * 1024**3,           # 10 GB
        100 * 1024**3,          # 100 GB
    ],
)

BODY_BYTES_TOTAL = Counter(
    "producer_body_bytes_total",
    "Total bytes received through ext_proc",
    ["method"],
)

# --- Cache metrics ---

CACHE_OPS = Counter(
    "producer_cache_operations_total",
    "Cache operations",
    ["operation"],
    # operation: hit, miss, store
)

# --- SDS metrics ---

SDS_CERTS_GENERATED = Counter(
    "producer_sds_certs_generated_total",
    "Dynamic TLS certificates generated by SDS handler",
)

SDS_ERRORS = Counter(
    "producer_sds_errors_total",
    "SDS certificate generation errors",
)
